=== SuhainaFathimaM/WebTechAssignment/files/student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" />
                <xs:element name="id" type="xs:int" />
                <xs:element name="department" type="xs:string" />
                <xs:element name="subjects">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="subject" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="code" type="xs:string" />
                                        <xs:element name="name" type="xs:string" />
                                        <xs:element name="credits" type="xs:int" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== SuhainaFathimaM/WebTechAssignment/files/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<student xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="student.xsd">
    <name>Suhaina Fathima M</name>
    <id>46</id>
    <department>Computer Science Engineering</department>
    <subjects>
        <subject>
            <code>22CS101</code>
            <name>Introduction to Programming</name>
            <credits>4</credits>
        </subject>
        <subject>
            <code>22CS102</code>
            <name>Data Structures</name>
            <credits>3</credits>
        </subject>
        <subject>
            <code>22SS501</code>
            <name>Web Technology</name>
            <credits>3</credits>
        </subject>
    </subjects>
</student>
